language: ruby
matrix:
  include:
    - rvm: "ruby-2.2.3"
      env:
        - DB=mysql
        - BUNDLER_ARGS="--without production postgres"
    - rvm: "ruby-2.2.3"
      env:
        - DB=postgres
        - BUNDLER_ARGS="--without production mysql"
    - rvm: "ruby-2.3.0"
      env:
        - DB=mysql
        - BUNDLER_ARGS="--without production postgres"
    - rvm: "ruby-2.3.0"
      env:
        - DB=postgres
        - BUNDLER_ARGS="--without production mysql"

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database travis_ci_test;' -U postgres;cp config/database.yml.travis.postgres config/database.yml; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS travis_ci_test;';cp config/database.yml.travis.mysql config/database.yml; fi"
  - bundle install $BUNDLER_ARGS --jobs=3 --retry=3 --deployment
  - RAILS_ENV=test bundle exec rake db:migrate db:seed
