language: ruby
rvm:
 - "ruby-2.2.3"
 - "ruby-2.2.4"
 - "ruby-2.3.0"
 - "ruby-head"

env:
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database travis_ci_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then cp config/database.yml.travis.postgres config/database.yml; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS travis_ci_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then cp config/database.yml.travis.mysql config/database.yml; fi"
  - RAILS_ENV=test bundle exec rake db:migrate db:seed
